# Generated by Django 2.2.24 on 2022-10-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_сomplaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сomplaint',
            old_name='сomplaint',
            new_name='сomplaint_text',
        ),
    ]
