# Generated by Django 2.2.24 on 2022-10-28 17:11
import phonenumbers
from django.db import migrations


def write_correct_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        try:
            phone_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
            flat.owner_pure_phone = f'+{phone_number.country_code}{phone_number.national_number}'
            flat.save()
        except phonenumbers.phonenumberutil.NumberParseException:
            flat.owner_pure_phone = ''
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(write_correct_phone_number),
    ]
