# Generated by Django 2.2.24 on 2022-10-28 20:35

from django.db import migrations


def copy_many_to_many_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners:
        flats = Flat.objects.filter(owner_pure_phone=owner.owner_pure_phone)
        for flat in flats:
            owner.owned_apartments.add(flat)
            owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20221028_2130'),
    ]

    operations = [
        migrations.RunPython(copy_many_to_many_field),
    ]
