# Generated by Django 2.2.24 on 2022-11-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20221101_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owned_apartments',
            new_name='apartments',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
        migrations.RenameField(
            model_name='сomplaint',
            old_name='сomplaint_text',
            new_name='сomplaint',
        ),
    ]
